baseURL = "https://kang8.github.io/"
languageCode = "en-us"
title = "Kang's Blog"
theme = "simple"

# hughlighting
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# 参数
[params]
    avatar = "https://cdn.jsdelivr.net/gh/yk17310320725/picBed/img/20200805204651.png"
    favicon = true
    math = true

# 导航栏
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# 图标
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/kang8"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/kang__98"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"

