license = "GPL-3.0-or-later"
tags = ["blog", "responsive", "clean", "simple", "light", "disqus", "commento", "mobile", "customizable", "minimalistic", "typography", "fontawesome", "reading"]
features = ["responsive", "clean", "disqus", "commento", "math", "fontawesome", "social-icons", "customizable", "RSS"]
